[project]
name = "midi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.2",
    "litellm>=1.80.7",
    "midi2audio>=0.1.1",
    "midiutil>=1.2.1",
    "mido>=1.3.3",
    "python-dotenv>=1.2.1",
]
